from __future__ import annotations

TOOLS: list[dict[str, object]] = [
    {
        "name": "search_jobs",
        "short": "sj",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 500,
        "desc": "Search LinkedIn jobs by keyword/location",
    },
    {
        "name": "search_jobs_multi",
        "short": "sjm",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 800,
        "desc": "Search ALL 5 job boards at once",
    },
    {
        "name": "get_job_details",
        "short": "gj",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 400,
        "desc": "Full job details + salary from URL",
    },
    {
        "name": "get_company_jobs",
        "short": "gcj",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 400,
        "desc": "All open jobs at a company",
    },
    {
        "name": "get_company_profile",
        "short": "gcp",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 300,
        "desc": "Company info from public signals",
    },
    {
        "name": "search_companies",
        "short": "sc",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 300,
        "desc": "Search companies by keyword",
    },
    {
        "name": "get_job_salary",
        "short": "gjs",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 250,
        "desc": "Extract salary from job posting",
    },
    {
        "name": "get_job_trends",
        "short": "gjt",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 400,
        "desc": "Hiring trends by role/location",
    },
    {
        "name": "get_industry_insights",
        "short": "gii",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 500,
        "desc": "Market insights for an industry",
    },
    {
        "name": "search_jobs_advanced",
        "short": "sja",
        "engine": "E1",
        "risk": "public_no_login_read_only",
        "tokens": 500,
        "desc": "Advanced search with all filters",
    },
    {
        "name": "analyze_resume",
        "short": "ar",
        "engine": "RE",
        "risk": "local_zero_account_risk",
        "tokens": 400,
        "desc": "Parse resume PDF/DOCX/text",
    },
    {
        "name": "get_resume_insights",
        "short": "gri",
        "engine": "RE",
        "risk": "local_zero_account_risk",
        "tokens": 300,
        "desc": "Skill gaps & improvement suggestions",
    },
    {
        "name": "match_jobs_to_resume",
        "short": "mjr",
        "engine": "ME",
        "risk": "local_zero_account_risk",
        "tokens": 1500,
        "desc": "Ranked job matches",
    },
    {
        "name": "compare_jobs",
        "short": "cj",
        "engine": "ME",
        "risk": "local_zero_account_risk",
        "tokens": 600,
        "desc": "Side-by-side job comparison",
    },
    {
        "name": "export_jobs",
        "short": "ej",
        "engine": "LO",
        "risk": "local_zero_account_risk",
        "tokens": 100,
        "desc": "Export to CSV/JSON",
    },
    {
        "name": "save_job_alert",
        "short": "sja",
        "engine": "ST",
        "risk": "local_zero_account_risk",
        "tokens": 100,
        "desc": "Save recurring job search",
    },
    {
        "name": "get_saved_alerts",
        "short": "gsa",
        "engine": "ST",
        "risk": "local_zero_account_risk",
        "tokens": 100,
        "desc": "List saved alerts",
    },
    {
        "name": "check_saved_alerts",
        "short": "csa",
        "engine": "E1+ST",
        "risk": "public_no_login_read_only",
        "tokens": 500,
        "desc": "Run all alerts for new matches",
    },
    {
        "name": "get_my_profile",
        "short": "gmp",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 700,
        "desc": "Your LinkedIn profile",
    },
    {
        "name": "get_person_profile",
        "short": "gpp",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 700,
        "desc": "View any person's profile",
    },
    {
        "name": "search_people",
        "short": "sp",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 600,
        "desc": "People search",
    },
    {
        "name": "get_my_connections",
        "short": "gmc",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 400,
        "desc": "Your connection list",
    },
    {
        "name": "get_inbox",
        "short": "gi",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 400,
        "desc": "Recent conversations",
    },
    {
        "name": "get_conversation",
        "short": "gco",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 500,
        "desc": "Read a conversation thread",
    },
    {
        "name": "get_feed",
        "short": "gf",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 600,
        "desc": "Your home feed posts",
    },
    {
        "name": "get_notifications",
        "short": "gn",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 300,
        "desc": "Your notifications",
    },
    {
        "name": "get_sidebar_profiles",
        "short": "gsp",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 400,
        "desc": "People you may know",
    },
    {
        "name": "get_company_employees",
        "short": "gce",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 600,
        "desc": "Employees at a company",
    },
    {
        "name": "check_session",
        "short": "cs",
        "engine": "E2",
        "risk": "browser_readonly_account_risk",
        "tokens": 200,
        "desc": "Check LinkedIn session status",
    },
    {
        "name": "get_engine_status",
        "short": "ges",
        "engine": "-",
        "risk": "local_zero_account_risk",
        "tokens": 200,
        "desc": "Show available engines",
    },
    {
        "name": "get_help",
        "short": "gh",
        "engine": "-",
        "risk": "local_zero_account_risk",
        "tokens": 300,
        "desc": "Tool documentation",
    },
    {
        "name": "get_usage_stats",
        "short": "gus",
        "engine": "-",
        "risk": "local_zero_account_risk",
        "tokens": 300,
        "desc": "Recent local usage and token estimates",
    },
    {
        "name": "get_tool_usage_summary",
        "short": "gtus",
        "engine": "-",
        "risk": "local_zero_account_risk",
        "tokens": 250,
        "desc": "Aggregate local usage by tool",
    },
    {
        "name": "reset_usage_stats",
        "short": "rus",
        "engine": "-",
        "risk": "local_zero_account_risk",
        "tokens": 100,
        "desc": "Reset local usage metrics",
    },
    {
        "name": "get_profile_voyager",
        "short": "gpv",
        "engine": "E3",
        "risk": "disabled_private_api_risk",
        "tokens": 300,
        "desc": "Lightweight profile (OFF)",
    },
]


def tool_help(tool: str = "") -> dict[str, object]:
    if tool:
        for row in TOOLS:
            if tool in {str(row["name"]), str(row["short"])}:
                return row
        return {"error": "unknown_tool", "tool": tool}
    return {"count": len(TOOLS), "tools": TOOLS}
